In [1]:
import numpy as np
from activate_function import softmax
from Loss_fucntion import cross_entropy_error

In [2]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)
    
    def predict(self, x):
        return np.dot(x,self.W)
    
    def loss(self,x,t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y,t)
        
        return loss

In [3]:
net = simpleNet()

In [4]:
print(net.W)

[[ 0.20281901 -2.17812409  1.14895243]
 [ 1.39807807  0.23485783  0.53201596]]


In [5]:
x = np.array([0.6,0.9])

In [6]:
p = net.predict(x)
print(p)

[ 1.37996167 -1.09550241  1.16818582]


In [7]:
np.argmax(p)

0

In [8]:
t = np.array([0,0,1])
net.loss(x,t)

0.8500811032006795

In [9]:
t = np.array([0,1,0])
net.loss(x,t)

3.113767312726485

In [10]:

def _numerical_gradient_no_batch(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 还原值
        
    return grad

In [11]:
def numerical_gradient(f, X):
    if X.ndim == 1:
        return _numerical_gradient_no_batch(f, X)
    else:
        grad = np.zeros_like(X)
        
        for idx, x in enumerate(X):
            grad[idx] = _numerical_gradient_no_batch(f, x)
        
        return grad

In [12]:
f = lambda w: net.loss(x,t)

In [13]:
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.3169113  -0.57333882  0.25642752]
 [ 0.47536695 -0.86000823  0.38464129]]
